baseURL = "https://mikihau.github.io/"
languageCode = "en-us"
title = "Miki's Blog"
theme = "hugo-journal"

[author]
  name = "Miki Hau"
  homepage = "https://mikihau.github.io/"

#[languages]
#  [languages.en]
#    contentDir = "content/posts"
#    languageName = "English"
#    weight = 2

[params]
  description = "This is Miki's blog."
  githubUsername = "mikihau"
  twitterUsername = "@miki_hau"
  tagline = ""
#[params.work]
#  jobTitle = "occupation"
#  company = "the company"
#  companyUrl = "https://the.company.url/"
#[params.gpg]
#  key = "0x1111111111111111"
#  fingerprint = "0000 0000 0000 0000 0000  0000 0000 0000 0000 0000"
#  link = "https://pgp.mit.edu/pks/lookup?op=get&search=0x1111111111111111"