baseURL = "https://mikihau.github.io/"
languageCode = "en-us"
title = "Miki's Blog"
theme = "yinyang"

[author]
  name = "Miki Hau"
  homepage = "https://mikihau.github.io/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 2

#[[params.socials]]
#name = "About"
#link = "https://mikihau.github.io/"